name: CICD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  cicd-pipeline:
    uses: samirmarin/github-actions-by-example-reusable-workflows/.github/workflows/reusable-cicd-pipeline.yaml@cicd-pipeline-reusable-workflow